// Generated by BIN2C

#pragma once

#include <Windows.h>

#if defined(__cplusplus)
extern "C" {
#endif

extern const unsigned char g_KduDbData[2031769];
extern const ULONG g_KduDbSize;

#if defined(__cplusplus)
}
#endif
