/*******************************************************************************
*
*  (C) COPYRIGHT AUTHORS, 2026
*
*  TITLE:       BIN2C.CPP
*
*  VERSION:     1.00
*
*  DATE:        28 Jul 2026
*
*  BIN2C - Binary to C array converter utility.
*
* THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
* ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED
* TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
* PARTICULAR PURPOSE.
*
*******************************************************************************/

#include <Windows.h>
#include <stdio.h>

#ifdef __cplusplus
extern "C" {
#include "../../Shared/ntos/ntos.h"
#include "../../Shared/minirtl/cmdline.h"
}
#endif

INT main(
    _In_ INT argc,
    _In_ CHAR* argv[]
)
{
    if (argc < 3) {
        printf("BIN2C - Binary to C Array Converter v1.00\n");
        printf("Usage: bin2c <input_file> <output_file> [array_name]\n");
        return -1;
    }

    LPCSTR inputPath = argv[1];
    LPCSTR outputPath = argv[2];
    LPCSTR arrayName = (argc >= 4) ? argv[3] : "rawData";

    HANDLE hInput = CreateFileA(inputPath, GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);
    if (hInput == INVALID_HANDLE_VALUE) {
        printf("Error: Cannot open input file %s (err %lu)\n", inputPath, GetLastError());
        return -1;
    }

    DWORD fileSize = GetFileSize(hInput, NULL);
    if (fileSize == INVALID_FILE_SIZE || fileSize == 0) {
        printf("Error: Invalid or empty file\n");
        CloseHandle(hInput);
        return -1;
    }

    BYTE* buffer = (BYTE*)HeapAlloc(GetProcessHeap(), 0, fileSize);
    if (!buffer) {
        printf("Error: Out of memory\n");
        CloseHandle(hInput);
        return -1;
    }

    DWORD bytesRead = 0;
    if (!ReadFile(hInput, buffer, fileSize, &bytesRead, NULL) || bytesRead != fileSize) {
        printf("Error: Failed reading input file\n");
        HeapFree(GetProcessHeap(), 0, buffer);
        CloseHandle(hInput);
        return -1;
    }
    CloseHandle(hInput);

    FILE* fOut = fopen(outputPath, "w");
    if (!fOut) {
        printf("Error: Cannot create output file %s\n", outputPath);
        HeapFree(GetProcessHeap(), 0, buffer);
        return -1;
    }

    fprintf(fOut, "// Generated by BIN2C\n\n");
    fprintf(fOut, "#pragma once\n\n");
    fprintf(fOut, "const unsigned char %s[%lu] = {\n", arrayName, fileSize);

    for (DWORD i = 0; i < fileSize; ++i) {
        if (i % 16 == 0) {
            fprintf(fOut, "    ");
        }
        fprintf(fOut, "0x%02X", buffer[i]);
        if (i + 1 < fileSize) {
            fprintf(fOut, ", ");
        }
        if ((i + 1) % 16 == 0 || i + 1 == fileSize) {
            fprintf(fOut, "\n");
        }
    }

    fprintf(fOut, "};\n");

    fclose(fOut);
    HeapFree(GetProcessHeap(), 0, buffer);

    printf("Successfully converted %s (%lu bytes) -> %s\n", inputPath, fileSize, outputPath);
    return 0;
}
